import * as React from 'react';
import { Download, Sparkles } from 'lucide-react';
import { Button, LoadingSkeleton } from '@/components/ui';
import { type PostEventIntelligence } from '@/lib/ai';
import { ai } from '@/lib/ai';
import { notify } from '@/lib/notification-store';
import { ExecutiveSummaryCard } from './ExecutiveSummaryCard';
import { KeyTakeawaysPanel } from './KeyTakeawaysPanel';
import { ActionItemsPanel } from './ActionItemsPanel';
import { TopicAnalysis } from './TopicAnalysis';
import { EngagementJourney } from './EngagementJourney';
import { SentimentInsights } from './SentimentInsights';
import { RecommendationPanel } from './RecommendationPanel';
import { CrossActivityAnalysis } from './CrossActivityAnalysis';

export function AIInsightsDashboard({ eventId }: { eventId: string }) {
  const [intel, setIntel] = React.useState<PostEventIntelligence | null>(null);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    let mounted = true;
    const fetchIntel = async () => {
      try {
        setLoading(true);
        const report = await ai.intelligence.generateIntelligence(eventId);
        if (mounted) {
          setIntel(report);
        }
      } catch (err) {
        console.error('Failed to load intelligence', err);
      } finally {
        if (mounted) setLoading(false);
      }
    };
    
    fetchIntel();
    return () => { mounted = false; };
  }, [eventId]);

  const handleExport = () => {
    notify({
      type: "success",
      description: "Your executive intelligence report is being generated and will download shortly."
    } as any);
  };

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="flex justify-between items-center mb-6">
          <LoadingSkeleton variant="title" className="w-48" />
          <LoadingSkeleton variant="block" className="w-32 h-10" />
        </div>
        <LoadingSkeleton variant="card" className="h-48" />
        <div className="grid md:grid-cols-2 gap-6">
          <LoadingSkeleton variant="card" className="h-64" />
          <LoadingSkeleton variant="card" className="h-64" />
        </div>
      </div>
    );
  }

  if (!intel) {
    return (
      <div className="text-center py-12 text-muted-foreground">
        Failed to load AI Intelligence. Please try again.
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-5xl mx-auto pb-12 animate-in fade-in duration-500">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-display font-semibold flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-brand" />
            AI Intelligence
          </h2>
          <p className="text-sm text-muted-foreground mt-1">Post-event analysis and executive insights generated by AI.</p>
        </div>
        
        <Button onClick={handleExport} className="gap-2 shrink-0">
          <Download className="h-4 w-4" />
          Export Report
        </Button>
      </div>

      <ExecutiveSummaryCard summary={intel.executiveSummary} />

      <div className="grid lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <ActionItemsPanel items={intel.actionItems} />
          <TopicAnalysis topics={intel.topicAnalysis} />
          <RecommendationPanel recommendations={intel.recommendations} followUps={intel.followUpSuggestions} />
        </div>
        
        <div className="space-y-6">
          <KeyTakeawaysPanel takeaways={intel.keyTakeaways} />
          <SentimentInsights overall={intel.sentimentIntelligence.overall} distribution={intel.sentimentIntelligence.distribution} />
          <EngagementJourney journey={intel.engagementJourney} />
          <CrossActivityAnalysis analysis={intel.crossActivityAnalysis} />
        </div>
      </div>
    </div>
  );
}
